import { Model, DataTypes, Sequelize } from 'sequelize';

export interface ExerciseListAttributes {
  id: number;
  name: string;
  userId: number;
  exercises: {
    exerciseType: string;
    exerciseData: Record<string, unknown>;
  }[];
  createdAt: Date;
  updatedAt: Date;
}

/** Attributes for create() – id, createdAt, updatedAt are auto-generated by the DB */
type ExerciseListCreationAttributes = Omit<ExerciseListAttributes, 'id' | 'createdAt' | 'updatedAt'> &
  Partial<Pick<ExerciseListAttributes, 'id' | 'createdAt' | 'updatedAt'>>;

export default (sequelize: Sequelize) => {
  class ExerciseList
    extends Model<ExerciseListAttributes, ExerciseListCreationAttributes>
    implements ExerciseListAttributes
  {
    declare id: number;
    declare name: string;
    declare userId: number;
    declare exercises: {
      exerciseType: string;
      exerciseData: Record<string, unknown>;
    }[];
    declare readonly createdAt: Date;
    declare readonly updatedAt: Date;
  }

  ExerciseList.init(
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      name: {
        type: DataTypes.STRING(255),
        allowNull: false,
        defaultValue: '',
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: { model: 'Users', key: 'id' },
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      },
      createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
      },
      updatedAt: {
        type: DataTypes.DATE,
        allowNull: false,
      },
      exercises: {
        type: DataTypes.JSON,
        allowNull: false,
        defaultValue: '[]',
        get(): unknown[] {
          const raw = this.getDataValue('exercises');
          if (Array.isArray(raw)) return raw;
          if (typeof raw !== 'string') return [];
          try {
            return JSON.parse(raw) as unknown[];
          } catch {
            return [];
          }
        },
        set(val: unknown) {
          const arr = Array.isArray(val)
            ? val
            : typeof val === 'string'
              ? (() => {
                  try {
                    const p = JSON.parse(val);
                    return Array.isArray(p) ? p : [];
                  } catch {
                    return [];
                  }
                })()
              : [];
          this.setDataValue('exercises', arr);
        },
      },
    },
    {
      sequelize,
      tableName: 'ExerciseList',
      timestamps: true,
    },
  );

  (ExerciseList as typeof ExerciseList & { associate: (models: Record<string, unknown>) => void }).associate = (
    models: Record<string, unknown>,
  ) => {
    ExerciseList.belongsTo(models.User as never, {
      as: 'user',
      foreignKey: { name: 'userId', allowNull: false },
    });
  };

  return ExerciseList;
};
